ls;
mv delivery/apples.txt fruit;
mv delivery/grapples.txt fruit;
mv delivery/tomatoes.txt fruit;
mv delivery/watermelon.txt fruit;
mv delivery/bison_burgers.txt meat;
mv delivery/hotdogs.txt meat;
mv delivery/lamb_ribs.txt meat;
mv delivery/salmon_steak.txt meat;
mv delivery/turkey_breast.txt meat;
mv delivery/brie.txt dairy;
mv delivery/fage_yogurt.txt dairy;
mv delivery/icecream.txt dairy;
mv delivery/land_o_lakes_butter.txt dairy;
mv delivery/milk.txt dairy;
mv delivery/velveeta_cheese.txt dairy;
mv delivery/broccoli.txt veggies;